[package]
name = "Solyrix Arena"
version = "1.0.0"
authors = ["Team Solyrix"]

[addresses]
room_manager = "0xbf63114b92ed90297f1886ede79305269d163a3b368ba8ff448f0b1b6a744bbb" # Will be replaced with your admin address
agent_template = "0x1" # Will be replaced with deployed address

[dev-addresses]
room_manager = "0xbf63114b92ed90297f1886ede79305269d163a3b368ba8ff448f0b1b6a744bbb"
agent_template = "0xbf63114b92ed90297f1886ede79305269d163a3b368ba8ff448f0b1b6a744bbb"

[dependencies.AptosFramework]
git    = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev    = "aptos-release-v1.29"

[dev-dependencies]